### ISSUE TITLE
YUV-to-RGB Conversion Shader

### ISSUE THREAD

**Issue by f3z0** [brion/yuv-canvas#16]
The YUV to RGB colorspace conversion should ideally be a shader program and executed on the GPU. This should make 4K video resolution playback feasible. Here's a working OpenGL example http://www.fourcc.org/source/YUV420P-OpenGL-GLSLang.c. BTW, YUV-Canvas is great, many thanks.

**Comment by f3z0** [comment]
Nevermind, looks like YCbCr.js isn't used.

**Comment by bvibber** [comment]
The WebGL shader is used when supported and yes it makes a big difference in performance. :) The in-JS conversion is used only if WebGL is unavailable (old browser versions or problematic video drivers) or explicitly disabled.
