### ISSUE TITLE
how to show gray picture

### ISSUE THREAD

**Issue by starhu521** [brion/yuv-canvas#24]
I can get the frame, and it only has Y bytes, there's no UV, if i don't set UY bytes to the frame, it will be green, but i just want to show a gray picture, so what can i do ?

**Comment by bvibber** [comment]
You can synthesize U and V planes of the required size, and then reuse them with each frame.

Use the value 0x80 (128) for the fill bytes, and I believe it should give you a nice grayscale output for your Y plane.

**Comment by starhu521** [comment]
thanks!
It works well
