### ISSUE TITLE
Why is my RENDERED YUV data have jagged

### ISSUE THREAD

**Issue by icyfe** [brion/yuv-canvas#30]
hi~ brion, i have e question , hope to get your answer，  now i get yuv data  and i set yuv-canvns width and height ,But Why are there serrations in the render    
![image](https://user-images.githubusercontent.com/44893721/91376457-a8c89700-e84f-11ea-9f81-9e27f6d35bd5.png)

**Comment by myseemylife** [comment]
your image link  is broken! # @icyfe
