### ISSUE TITLE
drawFrame abnormal

### ISSUE THREAD

**Issue by zhejinjiang** [brion/yuv-canvas#38]
i use ffmpeg to decode h265 data and use yuv-canvas to draw data.but on some device, it will show abnormal.like 👇
![image](https://user-images.githubusercontent.com/89907308/162138827-e11d606a-ff04-462f-aa13-8d2fd04c6bc2.png)

this problem destroyed me. can you give me some suggestion? thanks!!!

**Comment by bvibber** [comment]
I think I just worked around this bug actually -- try updating to 1.2.11 and see if that resolves it for you!

**Comment by zhejinjiang** [comment]
1.2.11 still have this problem, i will try other versions, thanks.

**Comment by bvibber** [comment]
Can you specify:
* device & GPU type
* operating system and version
* browser and version

**Comment by zhejinjiang** [comment]
build tool cache problem. 1.2.11 is ok, thanks again.
